// <auto-generated />
using System;
using FluxQuant.Server.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxQuant.Server.Migrations
{
    [DbContext(typeof(FluxQuantDbContext))]
    partial class FluxQuantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxQuant.Server.Domain.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentExcluded")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentValid")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQuota")
                        .HasColumnType("integer");

                    b.Property<int>("TaskPoolId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TaskPoolId", "UserId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.PoolAdjustmentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewQuota")
                        .HasColumnType("integer");

                    b.Property<int>("OldQuota")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TaskPoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("TaskPoolId");

                    b.ToTable("PoolAdjustmentLogs");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.ProductionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExcludedQty")
                        .HasColumnType("integer");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBackfill")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<int>("ValidQty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId", "LogDate");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.TaskPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuota")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("TaskPools");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Allocation", b =>
                {
                    b.HasOne("FluxQuant.Server.Domain.TaskPool", "TaskPool")
                        .WithMany("Allocations")
                        .HasForeignKey("TaskPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluxQuant.Server.Domain.User", "User")
                        .WithMany("Allocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaskPool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.PoolAdjustmentLog", b =>
                {
                    b.HasOne("FluxQuant.Server.Domain.User", "Operator")
                        .WithMany("AdjustmentLogs")
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxQuant.Server.Domain.TaskPool", "TaskPool")
                        .WithMany("AdjustmentLogs")
                        .HasForeignKey("TaskPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("TaskPool");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.ProductionLog", b =>
                {
                    b.HasOne("FluxQuant.Server.Domain.Allocation", "Allocation")
                        .WithMany("Logs")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Stage", b =>
                {
                    b.HasOne("FluxQuant.Server.Domain.Project", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.TaskPool", b =>
                {
                    b.HasOne("FluxQuant.Server.Domain.Stage", "Stage")
                        .WithMany("TaskPools")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Allocation", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Project", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.Stage", b =>
                {
                    b.Navigation("TaskPools");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.TaskPool", b =>
                {
                    b.Navigation("AdjustmentLogs");

                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("FluxQuant.Server.Domain.User", b =>
                {
                    b.Navigation("AdjustmentLogs");

                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
